export type SampleStudent = {
    firstName: string;
    lastName: string,
    courseCompletion: number,
    courseEngagment: number,
    projectDegree: number,
    teamProjectDegree: number,
    expectedTypeWork: string,
    targetWorkCity: string,
    expectedContractType: string,
    expectedSalary: number,
    canTakeApprenticeship: string,
    monthsOfCommercialExp: number,
    pictureUrl: string,
    availableTill: string
}

export const sampleStudents = [
        {
            firstName: "Mariusz",
            lastName: "Kowalski",
            courseCompletion: 4,
            courseEngagment: 5,
            projectDegree: 3,
            teamProjectDegree: 4,
            expectedTypeWork: "Na miejscu",
            targetWorkCity: "Warszawa",
            expectedContractType: "Tylko umowa o pracę",
            expectedSalary: 7500,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 3,
            pictureUrl: "https://randomuser.me/api/portraits/men/4.jpg",
            availableTill: "2023, 7, 15"

        },
        {
            firstName: "Helena",
            lastName: "Olszewska",
            courseCompletion: 2,
            courseEngagment: 1,
            projectDegree: 5,
            teamProjectDegree: 5,
            expectedTypeWork: "Na miejscu",
            targetWorkCity: "Warszawa",
            expectedContractType: "Możliwe B2B",
            expectedSalary: 19500,
            canTakeApprenticeship: "NIE",
            monthsOfCommercialExp: 32,
            pictureUrl: "https://randomuser.me/api/portraits/women/22.jpg",
            availableTill: "2023, 6, 15"

        },
        {
            firstName: "Krystian",
            lastName: "Poniatowski",
            courseCompletion: 3,
            courseEngagment: 4,
            projectDegree: 2,
            teamProjectDegree: 4,
            expectedTypeWork: "Nie ma znaczenia",
            targetWorkCity: "Chicago",
            expectedContractType: "Umowa zlecenie / dzieło",
            expectedSalary: 6950,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 1,
            pictureUrl: "https://randomuser.me/api/portraits/men/21.jpg",
            availableTill: "2023, 8, 11"

        },
        {
            firstName: "Antoni",
            lastName: "Macierewicz",
            courseCompletion: 1,
            courseEngagment: 1,
            projectDegree: 1,
            teamProjectDegree: 1,
            expectedTypeWork: "Przeprowadzka",
            targetWorkCity: "Smoleńsk",
            expectedContractType: "Brak preferencji",
            expectedSalary: 666,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 350,
            pictureUrl: "https://randomuser.me/api/portraits/men/20.jpg",
            availableTill: "2023, 7, 30"

        },
        {
            firstName: "Jacek",
            lastName: "Malinowski",
            courseCompletion: 2,
            courseEngagment: 2,
            projectDegree: 1,
            teamProjectDegree: 5,
            expectedTypeWork: "Praca zdalna",
            targetWorkCity: "Lublin",
            expectedContractType: "Możliwe B2B",
            expectedSalary: 9300,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 6,
            pictureUrl: "https://randomuser.me/api/portraits/men/19.jpg",
            availableTill: "2023, 6, 7"

        },
        {
            firstName: "Paweł",
            lastName: "Flis",
            courseCompletion: 3,
            courseEngagment: 4,
            projectDegree: 3,
            teamProjectDegree: 5,
            expectedTypeWork: "Praca hybrydowa",
            targetWorkCity: "Wrocław",
            expectedContractType: "Tylko umowa o pracę",
            expectedSalary: 7500,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 3,
            pictureUrl: "https://randomuser.me/api/portraits/men/18.jpg",
            availableTill: "2023, 6, 20"

        },
        {
            firstName: "Zbigniewa",
            lastName: "Ziobrzyńska",
            courseCompletion: 2,
            courseEngagment: 1,
            projectDegree: 4,
            teamProjectDegree: 4,
            expectedTypeWork: "Praca hybrydowa",
            targetWorkCity: "Kołobrzeg",
            expectedContractType: "Umowa zlecenie / dzieło",
            expectedSalary: 12500,
            canTakeApprenticeship: "NIE",
            monthsOfCommercialExp: 2,
            pictureUrl: "https://randomuser.me/api/portraits/women/17.jpg",
            availableTill: "2023, 7, 10"

        },
        {
            firstName: "Klemens",
            lastName: "Kleks",
            courseCompletion: 1,
            courseEngagment: 2,
            projectDegree: 3,
            teamProjectDegree: 4,
            expectedTypeWork: "Na miejscu",
            targetWorkCity: "Poznań",
            expectedContractType: "Brak preferencji",
            expectedSalary: 9200,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 5,
            pictureUrl: "https://randomuser.me/api/portraits/men/14.jpg",
            availableTill: "2023, 9, 11"

        },
        {
            firstName: "Wiktoria",
            lastName: "Cytryna",
            courseCompletion: 2,
            courseEngagment: 3,
            projectDegree: 5,
            teamProjectDegree: 4,
            expectedTypeWork: "Praca zdalna",
            targetWorkCity: "Szczecin",
            expectedContractType: "Tylko umowa o pracę",
            expectedSalary: 8000,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 4,
            pictureUrl: "https://randomuser.me/api/portraits/women/12.jpg",
            availableTill: "2023, 7, 15"

        },
        {
            firstName: "Janusz",
            lastName: "Muszyński",
            courseCompletion: 4,
            courseEngagment: 5,
            projectDegree: 5,
            teamProjectDegree: 4,
            expectedTypeWork: "Przeprowadzka",
            targetWorkCity: "Katowice",
            expectedContractType: "Możliwe B2B",
            expectedSalary: 7900,
            canTakeApprenticeship: "NIE",
            monthsOfCommercialExp: 7,
            pictureUrl: "https://randomuser.me/api/portraits/men/9.jpg",
            availableTill: "2023, 12, 24"

        },
        {
            firstName: "Anita",
            lastName: "Wąska",
            courseCompletion: 5,
            courseEngagment: 5,
            projectDegree: 5,
            teamProjectDegree: 5,
            expectedTypeWork: "Na miejscu",
            targetWorkCity: "Gdańsk",
            expectedContractType: "Brak preferencji",
            expectedSalary: 12000,
            canTakeApprenticeship: "NIE",
            monthsOfCommercialExp: 14,
            pictureUrl: "https://randomuser.me/api/portraits/women/43.jpg",
            availableTill: "2023, 6, 18"

        },
        {
            firstName: "Jarosław",
            lastName: "Gdybała",
            courseCompletion: 2,
            courseEngagment: 4,
            projectDegree: 2,
            teamProjectDegree: 4,
            expectedTypeWork: "Nie ma znaczenia",
            targetWorkCity: "Rzeszów",
            expectedContractType: "Na miejscu",
            expectedSalary: 9000,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 2,
            pictureUrl: "https://randomuser.me/api/portraits/men/65.jpg",
            availableTill: "2023, 9, 14"

        },
        {
            firstName: "Maria",
            lastName: "Wiśniewska",
            courseCompletion: 4,
            courseEngagment: 5,
            projectDegree: 2,
            teamProjectDegree: 5,
            expectedTypeWork: "Na miejscu",
            targetWorkCity: "Jastrzębie-Zdrój",
            expectedContractType: "Możliwe B2B",
            expectedSalary: 8700,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 5,
            pictureUrl: "https://randomuser.me/api/portraits/women/24.jpg",
            availableTill: "2023, 6, 8"

        },
        {
            firstName: "Andrzej",
            lastName: "Paprotka",
            courseCompletion: 3,
            courseEngagment: 4,
            projectDegree: 5,
            teamProjectDegree: 4,
            expectedTypeWork: "Praca zdalna",
            targetWorkCity: "Kraków",
            expectedContractType: "Na miejscu",
            expectedSalary: 9000,
            canTakeApprenticeship: "TAK",
            monthsOfCommercialExp: 2,
            pictureUrl: "https://randomuser.me/api/portraits/men/4.jpg",
            availableTill: "2023, 7, 2"
        },
    ]